# Generated by Django 5.2.5 on 2024-09-05 18:00

from django.db import migrations

SPECIALTIES = [
    "Antebellum Period",
    "Civil War History",
    "Reconstruction",
    "The New South / Jim Crow Era",
    "The Civil Rights Movement",
    "Slavery Studies",
    "Southern Politics",
    "Economic & Labor History",
    "Gender & Women's History",
    "African American History",
    "Cultural & Intellectual History",
    "Appalachian Studies",
    "Environmental History",
    "Military History",
    "Colonial South",
    "Modern South (Post-1965)",
    "Southern Religion",
    "Native American History of the South",
    "Public History & Memory Studies",
    "The Atlantic World / Transnational South",
    "Southern Foodways",
    "Southern Legal History",
]

def populate_specialties(apps, schema_editor):
    """Populates the Specialty table with a predefined list."""
    Specialty = apps.get_model('reviews', 'Specialty')
    for specialty_name in SPECIALTIES:
        Specialty.objects.get_or_create(name=specialty_name)

def remove_specialties(apps, schema_editor):
    """Removes the specialties added in the forward migration."""
    Specialty = apps.get_model('reviews', 'Specialty')
    Specialty.objects.filter(name__in=SPECIALTIES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_specialties, remove_specialties),
    ]
